Add database
gyngazov/java-filmorate pull request #3
Opened 2023-05-25 09:28 UTC by gyngazov

2023-05-25 18:35 UTC, EugeneLenkevich requested changes
Привет, Лев , спасибо за PR

В целом все отлично :)
Оставил пару пометок, вообще, чем мы больше специфической отбработки данных (сортировка, выборка и пр) переложим на СУБД тем, в общем случае, более оптимально :)

2023-05-25 18:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +        return Objects.hash(getId(), getEmail(), getLogin(), getName(), getBirthday());
Давай все же только по id считать, так же как в equals  :)

2023-05-25 18:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.getFilm(filmId) == null) {
Для проверки на существование можно делать exists-запрос, более эффективно чем всю запись из БД вытаскивать :)

https://stackoverflow.com/questions/7471625/fastest-check-if-row-exists-in-postgresql

2023-05-25 18:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .map(this::getUser)
Судя по всему тут для каждого id вызывается отдельный SQL-запрос, это не очень оптимально, особенно если идентификаторов будет много. А получится достать одним запросомчто то вроде
select * from user where id in(...//тут может быть запрос получения друзей)

2023-05-25 18:35 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +                .sorted()
.sorted()
                .limit(top)

Вот это точно стоит делать в самом sql-запросе, да и, тем более, не уверен что хорошая идея вытаскивать все записи из БД на сторону приложения чтобы получит только первые n, так же память модет кончиться, а вот СУБД влет справится :)

2023-05-26 08:15 UTC, gyngazov commented
Последний коммент касается InMemoryFilmStorage.java, в нем с бд не работаем.
В DbFilmStorage.java limit top помещен в sql-запрос, строка 226.

2023-05-26 12:42 UTC, EugeneLenkevich commented
> Последний коммент касается InMemoryFilmStorage.java, в нем с бд не работаем.

Ненужные классы можно кстати, почикать, чтобы не мешались. Если что они в гите есть

2023-05-29 06:35 UTC, merged